const spanish={top:'Un poquito de Ecuador. Aquí en Vermont.',navShop:'Descubre',navStory:'La tienda',navVisit:'Visítanos',directions:'Cómo llegar ↗',location:'SOUTH BURLINGTON, VERMONT',hero:'UN POQUITO<br>MÁS CERCA<br>DE <em>CASA.</em>',intro:'Los sabores, las tradiciones y los favoritos de Ecuador. Encuentra algo conocido o descubre algo nuevo en tu tienda latina local.',explore:'Explora la tienda ↓',come:'Ven a decir hola ↗',welcome:'BIENVENIDOS',photoLabel:'Tu comunidad.<br>Tus tradiciones.',ribbon:'PRODUCTOS ECUATORIANOS <b>✳</b> ROPA TRADICIONAL <b>✳</b> JOYERÍA BAÑADA EN ORO <b>✳</b> BIENVENIDOS',discoverEye:'UNA TIENDA PARA DESCUBRIR',discoverTitle:'TUS FAVORITOS.<br>NUEVOS HALLAZGOS.',discoverCopy:'Para la cocina, para una celebración o porque sí. Echa un vistazo y visítanos para conocer nuestra selección.',all:'Todo',food:'Alimentos y despensa',style:'Ropa y joyería',foodTitle:'UN SABOR DE ECUADOR',foodCopy:'Productos ecuatorianos y alimentos para los sabores que te gustan.',askFood:'Pregunta por los alimentos ↗',clothesTitle:'TRADICIÓN PARA VESTIR',clothesCopy:'Explora la ropa tradicional y encuentra una conexión con tu tierra.',askClothes:'Pregunta por la ropa ↗',jewelryArt:'Un toque dorado.',jewelryTitle:'ALGO QUE BRILLA',jewelryCopy:'Joyería bañada en oro para un regalo especial o un detalle de todos los días.',askJewelry:'Pregunta por la joyería ↗',availability:'La selección cambia. Llama para consultar productos, tallas y precios antes de hacer un viaje especial.',storyEye:'RAÍCES EN ECUADOR. AQUÍ EN VERMONT.',storyTitle:'UNA TIENDA.<br>UNA CONEXIÓN<br>CON <em>CASA.</em>',storyCopy:'Guallpa Latin Store ofrece productos ecuatorianos, ropa tradicional y joyería bañada en oro en South Burlington. Entra y descubre un poquito de Ecuador en Williston Road.',storyMore:'¿Buscas algo en particular? Llámanos o visítanos para conocer la selección.',facebook:'Novedades en Facebook ↗',visitEye:'ESTAMOS CERCA DE TI',visitTitle:'VEN A DECIR <em>HOLA.</em>',visitCopy:'Haz una parada en South Burlington. Nos encantará darte la bienvenida.',find:'ENCUÉNTRANOS',hours:'HORARIO',days:'Martes–domingo',monday:'Lunes',closed:'Cerrado',holiday:'El horario puede variar en días festivos. Llama para confirmar.',contact:'HABLEMOS',callCopy:'¿Tienes preguntas sobre un producto? Llámanos.',openMap:'Abrir en Google Maps ↗',closingEye:'DESDE ECUADOR, CON CARIÑO.',closingTitle:'NOS VEMOS PRONTO.',closingCopy:'Te esperamos en Guallpa Latin Store.',call:'Llama a la tienda'};
const elements=[...document.querySelectorAll('[data-i18n]')];
const english=Object.fromEntries(elements.map(e=>[e.dataset.i18n,e.innerHTML]));
let language='en';
try{language=localStorage.getItem('guallpa-language')==='es'?'es':'en'}catch{}
function updateStatus(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'numeric',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));const open=parts.weekday!=='Mon'&&Number(parts.hour)>=8&&Number(parts.hour)<20;document.querySelector('#status').textContent=language==='es'?(open?'Abierto ahora · Hasta las 8 PM':'Cerrado ahora · Mar–dom, 8 AM–8 PM'):(open?'Open now · Until 8 PM':'Closed now · Tue–Sun, 8 AM–8 PM');document.querySelector('.dot').style.background=open?'#58703f':'#8a7560'}
function renderLanguage(){elements.forEach(e=>{e.innerHTML=(language==='es'?spanish:english)[e.dataset.i18n]??english[e.dataset.i18n]});document.documentElement.lang=language;const button=document.querySelector('#language');button.textContent=language==='es'?'EN':'ES';button.setAttribute('aria-label',language==='es'?'Switch to English':'Cambiar a español');document.querySelector('.skip').textContent=language==='es'?'Saltar al contenido':'Skip to content';updateStatus()}
document.querySelector('#language').addEventListener('click',()=>{language=language==='en'?'es':'en';try{localStorage.setItem('guallpa-language',language)}catch{}renderLanguage()});
const menu=document.querySelector('#menu-toggle'),nav=document.querySelector('#navigation');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu')}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();menu.focus()}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('[data-category]').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter)}));
document.querySelector('#year').textContent=new Date().getFullYear();renderLanguage();setInterval(updateStatus,60000);
